<<<<<<< HEAD
server:
  port: 8080

spring:
  application:
    name:Software_Eng
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    //각자 db id랑 pw 입력
    username: user_codingrecipe
    password: 1234
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
<<<<<<< HEAD
#      // entity 관련 옵션(class 생성, 변경 관련)
=======
server:
  port: 8084

spring:
  application:
    name:Software_Eng
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    각자 pc에 만들어놓은 database
    url: jdbc:mysql://localhost:13306/db_software_eng?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    mysql에 생성한 사용자 계정 정보
    username: daneck
    password: 1234
  thymeleaf:
      cache: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
#      // entity 관련 옵션(class 생성, 변경 관련)
>>>>>>> b01b163 (Initial commit)
      ddl-auto: update
=======
      ddl-auto: update
>>>>>>> 94699e06d5c3e8d90d0e533efaa194ad7ed32ef5
